# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy custom HTML file into Nginx web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 so we can access Nginx
EXPOSE 80
